# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0004_auto_20170519_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='image',
            field=models.ImageField(blank=True, default='book.png', null=True, upload_to=''),
        ),
    ]
